### PR TITLE
Add more functional code

### PR DESCRIPTION
**Pull request by hugooliveirad**
_Do not merge yet_

Hey, this PR reimplements idle.js with a more functional code.

I didn't get rid of `prototype` yet, but I was able to minimize impure and stateful functions to bare minimum.

When I have more time I can go through the code and explain to you the design decisions.

To test it, I created a `examples/simple.js` with this content:

``` javascript
var Idle = require('../index');

var idle = new Idle({
  preset: 'bullets',
  moonwalk: true
});

idle.start();
```

### CODE REVIEW

**Comment by rafaelrinaldi** [comment]
@hugobessaa Aw man, thanks for this! As you know, I just started learning FP and to have a comparison like this to guide me through is really helpful.

Not sure if I'm ever going to merge it though since this library is very simple and already does pretty much what I want, but I will keep this for sure!

i love you

**Comment by hugooliveirad** [comment]
I just want to show my functional love. Don't bother to merge :smile:

**Comment by hugooliveirad** [comment]
Some highlights:
1. Prototype methods simply manage our pure and stateless helpers
2. Any function there can be exported and tested without creating an instance of `idle`.

Future improvements:
1. Provide custom write function to `render`, making it easy to test it

**Comment by hugooliveirad** [comment]
Oh, and look: not a single line were added.

**Comment by rafaelrinaldi** [comment]
@hugobessaa You might wanna check the latest release which was implemented using a more functional approach :+1:

**Comment by hugooliveirad** [comment]
Looks great!

**Pull request closed without merging**
